"""create_admins_stores_workers_opticians_roles_tables

Revision ID: 19bf4bfa7d32
Revises: 
Create Date: 2026-06-02 14:51:30.488471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19bf4bfa7d32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('business_name', sa.String(length=255), nullable=False, comment='Name of the optical store business'),
    sa.Column('owner_first_name', sa.String(length=100), nullable=False, comment="Owner's first name"),
    sa.Column('owner_last_name', sa.String(length=100), nullable=False, comment="Owner's last name"),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique email — used as login identifier'),
    sa.Column('phone', sa.String(length=10), nullable=False, comment='10-digit phone number'),
    sa.Column('password_hash', sa.Text(), nullable=False, comment="bcrypt hash (cost=12) of the admin's password"),
    sa.Column('profile_image', sa.Text(), nullable=True, comment='URL or path to profile image'),
    sa.Column('gst_number', sa.String(length=15), nullable=True, comment='GST registration number'),
    sa.Column('pan_number', sa.String(length=10), nullable=True, comment='PAN card number'),
    sa.Column('address', sa.Text(), nullable=False, comment='Full address'),
    sa.Column('city', sa.String(length=100), nullable=False, comment='City name'),
    sa.Column('state', sa.String(length=100), nullable=False, comment='State name'),
    sa.Column('pincode', sa.String(length=6), nullable=False, comment='6-digit pincode'),
    sa.Column('is_email_verified', sa.Boolean(), server_default='true', nullable=False, comment='Whether the email has been verified'),
    sa.Column('is_phone_verified', sa.Boolean(), server_default='true', nullable=False, comment='Whether the phone has been verified'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='admin_status_enum', create_constraint=True), server_default='ACTIVE', nullable=False, comment='Account status: ACTIVE, INACTIVE, or SUSPENDED'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Updated on every successful login'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp — NULL means active'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_phone'), 'admins', ['phone'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('token_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Auto-generated UUID primary key'),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='FK → admins.id — owner of this token'),
    sa.Column('token_hash', sa.Text(), nullable=False, comment='SHA-256 hash of the raw JWT refresh token'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='When this refresh token expires (UTC)'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='NULL = still valid; timestamp = revoked at that time'),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=True, comment='Optional browser/device identifier for audit'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (set by DB)'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_admin_id'), 'refresh_tokens', ['admin_id'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='FK → admins.id — owner of this store'),
    sa.Column('store_name', sa.String(length=255), nullable=False, comment='Display name of the store'),
    sa.Column('store_code', sa.String(length=50), nullable=False, comment='Unique store identifier code'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Store contact email'),
    sa.Column('phone', sa.String(length=10), nullable=False, comment='Store contact phone (10 digits)'),
    sa.Column('address', sa.Text(), nullable=False, comment='Full store address'),
    sa.Column('city', sa.String(length=100), nullable=False, comment='City name'),
    sa.Column('state', sa.String(length=100), nullable=False, comment='State name'),
    sa.Column('pincode', sa.String(length=6), nullable=False, comment='6-digit pincode'),
    sa.Column('gst_number', sa.String(length=15), nullable=True, comment='Store-level GST registration number'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether the store is currently active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp — NULL means active'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_admin_id'), 'stores', ['admin_id'], unique=False)
    op.create_index(op.f('ix_stores_store_code'), 'stores', ['store_code'], unique=True)
    op.create_table('opticians',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('store_id', sa.BigInteger(), nullable=False, comment='FK → stores.id — the store this optician belongs to'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment="Optician's first name"),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment="Optician's last name"),
    sa.Column('email', sa.String(length=255), nullable=True, comment="Optician's email (optional but unique if provided)"),
    sa.Column('phone', sa.String(length=10), nullable=False, comment='10-digit phone number'),
    sa.Column('password_hash', sa.Text(), nullable=False, comment="bcrypt hash (cost=12) of the optician's password"),
    sa.Column('profile_image', sa.Text(), nullable=True, comment='URL or path to profile image'),
    sa.Column('employee_code', sa.String(length=50), nullable=False, comment='Unique employee identifier code'),
    sa.Column('qualification', sa.String(length=255), nullable=True, comment='Professional qualification (e.g., B.Optom, M.Optom)'),
    sa.Column('joining_date', sa.Date(), nullable=False, comment='Date the optician joined'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether the optician is currently active'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Updated on every successful login'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp — NULL means active'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opticians_email'), 'opticians', ['email'], unique=True)
    op.create_index(op.f('ix_opticians_employee_code'), 'opticians', ['employee_code'], unique=True)
    op.create_index(op.f('ix_opticians_phone'), 'opticians', ['phone'], unique=True)
    op.create_index(op.f('ix_opticians_store_id'), 'opticians', ['store_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('store_id', sa.BigInteger(), nullable=False, comment='FK → stores.id — the store this role belongs to'),
    sa.Column('role_name', sa.String(length=50), nullable=False, comment='Role identifier — e.g., worker, optician, manager, cashier'),
    sa.Column('description', sa.Text(), nullable=True, comment="Human-readable description of the role's permissions"),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether this role is currently active in the store'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'role_name', name='uq_store_role')
    )
    op.create_index(op.f('ix_roles_store_id'), 'roles', ['store_id'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('store_id', sa.BigInteger(), nullable=False, comment='FK → stores.id — the store this worker belongs to'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment="Worker's first name"),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment="Worker's last name"),
    sa.Column('email', sa.String(length=255), nullable=True, comment="Worker's email (optional but unique if provided)"),
    sa.Column('phone', sa.String(length=10), nullable=False, comment='10-digit phone number'),
    sa.Column('password_hash', sa.Text(), nullable=False, comment="bcrypt hash (cost=12) of the worker's password"),
    sa.Column('profile_image', sa.Text(), nullable=True, comment='URL or path to profile image'),
    sa.Column('employee_code', sa.String(length=50), nullable=False, comment='Unique employee identifier code'),
    sa.Column('joining_date', sa.Date(), nullable=False, comment='Date the worker joined'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether the worker is currently active'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Updated on every successful login'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp — NULL means active'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_email'), 'workers', ['email'], unique=True)
    op.create_index(op.f('ix_workers_employee_code'), 'workers', ['employee_code'], unique=True)
    op.create_index(op.f('ix_workers_phone'), 'workers', ['phone'], unique=True)
    op.create_index(op.f('ix_workers_store_id'), 'workers', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workers_store_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_phone'), table_name='workers')
    op.drop_index(op.f('ix_workers_employee_code'), table_name='workers')
    op.drop_index(op.f('ix_workers_email'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_roles_store_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_opticians_store_id'), table_name='opticians')
    op.drop_index(op.f('ix_opticians_phone'), table_name='opticians')
    op.drop_index(op.f('ix_opticians_employee_code'), table_name='opticians')
    op.drop_index(op.f('ix_opticians_email'), table_name='opticians')
    op.drop_table('opticians')
    op.drop_index(op.f('ix_stores_store_code'), table_name='stores')
    op.drop_index(op.f('ix_stores_admin_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_refresh_tokens_admin_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_admins_phone'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
