"""Add V2 Hierarchical Permission System

Revision ID: 33d677afc8b2
Revises: b1c2d3e4f5a6
Create Date: 2026-06-27 15:16:39.376129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d677afc8b2'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('header_text', sa.String(length=255), nullable=True),
    sa.Column('sub_header_text', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('gst_number', sa.String(length=100), nullable=True),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('show_prescription', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_gst', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('theme_color', sa.String(length=50), nullable=True),
    sa.Column('footer_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_settings_store_id'), 'bill_settings', ['store_id'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=220), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_dangerous', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module', 'action', name='uq_permission_module_action')
    )
    op.create_index(op.f('ix_permissions_key'), 'permissions', ['key'], unique=True)
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_table('super_admins',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('profile_image', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='superadmin_status_enum', create_constraint=True), server_default='ACTIVE', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_super_admins_email'), 'super_admins', ['email'], unique=True)
    op.create_table('global_role_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_type', sa.Enum('ADMIN', 'MANAGER', 'WORKER', 'OPTICIAN', 'ACCOUNTANT', name='permission_role_type_enum', create_constraint=True), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('is_granted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_by_superadmin_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_superadmin_id'], ['super_admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_type', 'permission_id', name='uq_global_role_permission')
    )
    op.create_index(op.f('ix_global_role_permissions_permission_id'), 'global_role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_global_role_permissions_role_type'), 'global_role_permissions', ['role_type'], unique=False)
    op.create_table('user_permission_overrides',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_type', sa.Enum('ADMIN', 'MANAGER', 'WORKER', 'OPTICIAN', 'ACCOUNTANT', name='permission_user_type_enum', create_constraint=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Polymorphic FK — admins/managers/workers/opticians/accountants.id'),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('is_granted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('granted_by_id', sa.BigInteger(), nullable=False),
    sa.Column('set_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_type', 'user_id', 'permission_id', name='uq_user_permission_override')
    )
    op.create_index(op.f('ix_user_permission_overrides_permission_id'), 'user_permission_overrides', ['permission_id'], unique=False)
    op.create_index(op.f('ix_user_permission_overrides_user_id'), 'user_permission_overrides', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_permission_overrides_user_type'), 'user_permission_overrides', ['user_type'], unique=False)
    op.create_index(op.f('ix_user_permission_overrides_admin_id'), 'user_permission_overrides', ['admin_id'], unique=False)
    op.create_table('accountants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='FK → admins.id — the business this accountant belongs to'),
    sa.Column('store_id', sa.BigInteger(), nullable=True, comment='NULL = business-level accountant'),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('profile_image', sa.Text(), nullable=True),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accountants_admin_id'), 'accountants', ['admin_id'], unique=False)
    op.create_index(op.f('ix_accountants_store_id'), 'accountants', ['store_id'], unique=False)
    op.create_index(op.f('ix_accountants_email'), 'accountants', ['email'], unique=True)
    op.create_index(op.f('ix_accountants_employee_code'), 'accountants', ['employee_code'], unique=True)
    op.create_index(op.f('ix_accountants_phone'), 'accountants', ['phone'], unique=True)
    op.create_table('admin_role_permission_overrides',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='The business this role-level override belongs to'),
    sa.Column('role_type', sa.Enum('ADMIN', 'MANAGER', 'WORKER', 'OPTICIAN', 'ACCOUNTANT', name='permission_role_type_enum', create_constraint=True), nullable=False, comment='MANAGER / WORKER / OPTICIAN / ACCOUNTANT only — never ADMIN'),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('is_granted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id', 'role_type', 'permission_id', name='uq_admin_role_permission_override')
    )
    op.create_index(op.f('ix_admin_role_permission_overrides_admin_id'), 'admin_role_permission_overrides', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_role_permission_overrides_permission_id'), 'admin_role_permission_overrides', ['permission_id'], unique=False)
    op.create_index(op.f('ix_admin_role_permission_overrides_role_type'), 'admin_role_permission_overrides', ['role_type'], unique=False)

    op.alter_column('inventory_transactions', 'product_snapshot_id',
               existing_type=sa.BIGINT(),
               comment='FK → product_snapshots.id — frozen copy of the product at time of this movement.  Use for damage/loss/return value reporting.',
               existing_comment='FK → product_snapshots.id — frozen product copy at transaction time',
               existing_nullable=True)
    op.alter_column('inventory_transactions', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Per-unit value at time of this movement — snapshotted so that later price changes do not alter historical valuations.',
               existing_comment='Per-unit value at time of this movement',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'product_id',
               existing_type=sa.BIGINT(),
               comment='FK → products.id — soft reference; SET NULL if the live product is deleted.  The snapshot remains intact regardless.',
               existing_comment='FK → products.id — soft reference; SET NULL if the live product is deleted',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'sku',
               existing_type=sa.VARCHAR(length=100),
               comment='SKU copied from products.sku at time of snapshot',
               existing_comment='SKU copied from products.sku',
               existing_nullable=False)
    op.alter_column('product_snapshots', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Product name copied from products.name at time of snapshot',
               existing_comment='Product name at time of snapshot',
               existing_nullable=False)
    op.alter_column('product_snapshots', 'brand_id',
               existing_type=sa.BIGINT(),
               comment='Original brands.id (informational only — no FK constraint)',
               existing_comment='Original brands.id (informational)',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'brand_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Brand name copied at time of snapshot',
               existing_comment='Brand name at snapshot time',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'category_id',
               existing_type=sa.BIGINT(),
               comment='Original categories.id (informational only)',
               existing_comment='Original categories.id (informational)',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'category_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Category name copied at time of snapshot',
               existing_comment='Category name at snapshot time',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'subcategory_id',
               existing_type=sa.BIGINT(),
               comment='Original subcategories.id (informational only)',
               existing_comment='Original subcategories.id (informational)',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'subcategory_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Subcategory name copied at time of snapshot',
               existing_comment='Subcategory name at snapshot time',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'cost_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Cost price copied from products.cost_price at snapshot time',
               existing_comment='Cost price at snapshot time',
               existing_nullable=False)
    op.alter_column('product_snapshots', 'selling_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Selling price copied from products.selling_price at snapshot time',
               existing_comment='Selling price at snapshot time',
               existing_nullable=False)
    op.alter_column('product_snapshots', 'discount_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Default discount % copied from products.discount_percent',
               existing_comment='Default discount % at snapshot time',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('product_snapshots', 'warranty_months',
               existing_type=sa.INTEGER(),
               comment='Warranty duration copied from products.warranty_months',
               existing_comment='Warranty duration at snapshot time',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('product_snapshots', 'image_url',
               existing_type=sa.TEXT(),
               comment='Product image URL at time of snapshot',
               existing_comment='Product image URL at snapshot time',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'frame_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Frame type e.g. Full-Rim, Half-Rim, Rimless',
               existing_comment='Frame type',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'frame_shape',
               existing_type=sa.VARCHAR(length=100),
               comment='Frame shape e.g. Rectangle, Round, Aviator',
               existing_comment='Frame shape',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'frame_material',
               existing_type=sa.VARCHAR(length=100),
               comment='Frame material e.g. Acetate, Metal, TR-90',
               existing_comment='Frame material',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'gender',
               existing_type=sa.VARCHAR(length=100),
               comment='Target gender e.g. Male, Female, Unisex',
               existing_comment='Target gender',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'age_group',
               existing_type=sa.VARCHAR(length=100),
               comment='Target age group e.g. Adult, Kids',
               existing_comment='Target age group',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'lens_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Lens type e.g. Single Vision, Bifocal, Progressive',
               existing_comment='Lens type',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'lens_material',
               existing_type=sa.VARCHAR(length=100),
               comment='Lens material e.g. CR-39, Polycarbonate',
               existing_comment='Lens material',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'index_value',
               existing_type=sa.VARCHAR(length=100),
               comment='Refractive index e.g. 1.50, 1.60, 1.74',
               existing_comment='Refractive index',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'coating',
               existing_type=sa.VARCHAR(length=100),
               comment='Coating e.g. Anti-Reflective, HMC',
               existing_comment='Coating type',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'tint_color',
               existing_type=sa.VARCHAR(length=100),
               comment='Tint color if applicable',
               existing_comment='Tint color',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'uv_protection',
               existing_type=sa.VARCHAR(length=100),
               comment='UV protection level e.g. UV400',
               existing_comment='UV protection level',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'photochromic',
               existing_type=sa.VARCHAR(length=100),
               comment='Photochromic / transition capability',
               existing_comment='Photochromic capability',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'accessory_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Accessory type e.g. Case, Cloth, Chain, Solution',
               existing_comment='Accessory type',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'accessory_size',
               existing_type=sa.VARCHAR(length=100),
               comment='Accessory size / dimensions',
               existing_comment='Accessory size',
               existing_nullable=True)
    op.alter_column('purchase_order_items', 'product_id',
               existing_type=sa.BIGINT(),
               comment='FK → products.id — product being ordered (live catalogue reference)',
               existing_comment='FK → products.id — product being ordered',
               existing_nullable=False)
    op.alter_column('purchase_order_items', 'product_snapshot_id',
               existing_type=sa.BIGINT(),
               comment='FK → product_snapshots.id — frozen copy of the product as it was at the time this purchase order was created.  Use this for PO reports and cost tracking; never join products directly for price/name.',
               existing_comment='FK → product_snapshots.id — frozen product copy at PO creation time',
               existing_nullable=True)
    op.add_column('refresh_tokens', sa.Column('superadmin_id', sa.BigInteger(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('accountant_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_refresh_tokens_accountant_id'), 'refresh_tokens', ['accountant_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_superadmin_id'), 'refresh_tokens', ['superadmin_id'], unique=False)
    op.create_foreign_key(None, 'refresh_tokens', 'accountants', ['accountant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'refresh_tokens', 'super_admins', ['superadmin_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sale_items', 'product_id',
               existing_type=sa.BIGINT(),
               comment='FK → products.id — product sold (live catalogue reference)',
               existing_comment='FK → products.id — product sold',
               existing_nullable=False)
    op.alter_column('sale_items', 'product_snapshot_id',
               existing_type=sa.BIGINT(),
               comment='FK → product_snapshots.id — frozen copy of the product as it was at the moment of this sale.  Use this for invoices and reports; never join products directly for price/name data.',
               existing_comment='FK → product_snapshots.id — frozen product copy at sale time',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_items', 'product_snapshot_id',
               existing_type=sa.BIGINT(),
               comment='FK → product_snapshots.id — frozen product copy at sale time',
               existing_comment='FK → product_snapshots.id — frozen copy of the product as it was at the moment of this sale.  Use this for invoices and reports; never join products directly for price/name data.',
               existing_nullable=True)
    op.alter_column('sale_items', 'product_id',
               existing_type=sa.BIGINT(),
               comment='FK → products.id — product sold',
               existing_comment='FK → products.id — product sold (live catalogue reference)',
               existing_nullable=False)
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_superadmin_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_accountant_id'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'accountant_id')
    op.drop_column('refresh_tokens', 'superadmin_id')
    op.alter_column('purchase_order_items', 'product_snapshot_id',
               existing_type=sa.BIGINT(),
               comment='FK → product_snapshots.id — frozen product copy at PO creation time',
               existing_comment='FK → product_snapshots.id — frozen copy of the product as it was at the time this purchase order was created.  Use this for PO reports and cost tracking; never join products directly for price/name.',
               existing_nullable=True)
    op.alter_column('purchase_order_items', 'product_id',
               existing_type=sa.BIGINT(),
               comment='FK → products.id — product being ordered',
               existing_comment='FK → products.id — product being ordered (live catalogue reference)',
               existing_nullable=False)
    op.alter_column('product_snapshots', 'accessory_size',
               existing_type=sa.VARCHAR(length=100),
               comment='Accessory size',
               existing_comment='Accessory size / dimensions',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'accessory_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Accessory type',
               existing_comment='Accessory type e.g. Case, Cloth, Chain, Solution',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'photochromic',
               existing_type=sa.VARCHAR(length=100),
               comment='Photochromic capability',
               existing_comment='Photochromic / transition capability',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'uv_protection',
               existing_type=sa.VARCHAR(length=100),
               comment='UV protection level',
               existing_comment='UV protection level e.g. UV400',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'tint_color',
               existing_type=sa.VARCHAR(length=100),
               comment='Tint color',
               existing_comment='Tint color if applicable',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'coating',
               existing_type=sa.VARCHAR(length=100),
               comment='Coating type',
               existing_comment='Coating e.g. Anti-Reflective, HMC',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'index_value',
               existing_type=sa.VARCHAR(length=100),
               comment='Refractive index',
               existing_comment='Refractive index e.g. 1.50, 1.60, 1.74',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'lens_material',
               existing_type=sa.VARCHAR(length=100),
               comment='Lens material',
               existing_comment='Lens material e.g. CR-39, Polycarbonate',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'lens_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Lens type',
               existing_comment='Lens type e.g. Single Vision, Bifocal, Progressive',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'age_group',
               existing_type=sa.VARCHAR(length=100),
               comment='Target age group',
               existing_comment='Target age group e.g. Adult, Kids',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'gender',
               existing_type=sa.VARCHAR(length=100),
               comment='Target gender',
               existing_comment='Target gender e.g. Male, Female, Unisex',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'frame_material',
               existing_type=sa.VARCHAR(length=100),
               comment='Frame material',
               existing_comment='Frame material e.g. Acetate, Metal, TR-90',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'frame_shape',
               existing_type=sa.VARCHAR(length=100),
               comment='Frame shape',
               existing_comment='Frame shape e.g. Rectangle, Round, Aviator',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'frame_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Frame type',
               existing_comment='Frame type e.g. Full-Rim, Half-Rim, Rimless',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'image_url',
               existing_type=sa.TEXT(),
               comment='Product image URL at snapshot time',
               existing_comment='Product image URL at time of snapshot',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'warranty_months',
               existing_type=sa.INTEGER(),
               comment='Warranty duration at snapshot time',
               existing_comment='Warranty duration copied from products.warranty_months',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('product_snapshots', 'discount_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Default discount % at snapshot time',
               existing_comment='Default discount % copied from products.discount_percent',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('product_snapshots', 'selling_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Selling price at snapshot time',
               existing_comment='Selling price copied from products.selling_price at snapshot time',
               existing_nullable=False)
    op.alter_column('product_snapshots', 'cost_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Cost price at snapshot time',
               existing_comment='Cost price copied from products.cost_price at snapshot time',
               existing_nullable=False)
    op.alter_column('product_snapshots', 'subcategory_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Subcategory name at snapshot time',
               existing_comment='Subcategory name copied at time of snapshot',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'subcategory_id',
               existing_type=sa.BIGINT(),
               comment='Original subcategories.id (informational)',
               existing_comment='Original subcategories.id (informational only)',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'category_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Category name at snapshot time',
               existing_comment='Category name copied at time of snapshot',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'category_id',
               existing_type=sa.BIGINT(),
               comment='Original categories.id (informational)',
               existing_comment='Original categories.id (informational only)',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'brand_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Brand name at snapshot time',
               existing_comment='Brand name copied at time of snapshot',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'brand_id',
               existing_type=sa.BIGINT(),
               comment='Original brands.id (informational)',
               existing_comment='Original brands.id (informational only — no FK constraint)',
               existing_nullable=True)
    op.alter_column('product_snapshots', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Product name at time of snapshot',
               existing_comment='Product name copied from products.name at time of snapshot',
               existing_nullable=False)
    op.alter_column('product_snapshots', 'sku',
               existing_type=sa.VARCHAR(length=100),
               comment='SKU copied from products.sku',
               existing_comment='SKU copied from products.sku at time of snapshot',
               existing_nullable=False)
    op.alter_column('product_snapshots', 'product_id',
               existing_type=sa.BIGINT(),
               comment='FK → products.id — soft reference; SET NULL if the live product is deleted',
               existing_comment='FK → products.id — soft reference; SET NULL if the live product is deleted.  The snapshot remains intact regardless.',
               existing_nullable=True)
    op.alter_column('inventory_transactions', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Per-unit value at time of this movement',
               existing_comment='Per-unit value at time of this movement — snapshotted so that later price changes do not alter historical valuations.',
               existing_nullable=True)
    op.alter_column('inventory_transactions', 'product_snapshot_id',
               existing_type=sa.BIGINT(),
               comment='FK → product_snapshots.id — frozen product copy at transaction time',
               existing_comment='FK → product_snapshots.id — frozen copy of the product at time of this movement.  Use for damage/loss/return value reporting.',
               existing_nullable=True)

    op.drop_index(op.f('ix_admin_role_permission_overrides_role_type'), table_name='admin_role_permission_overrides')
    op.drop_index(op.f('ix_admin_role_permission_overrides_permission_id'), table_name='admin_role_permission_overrides')
    op.drop_index(op.f('ix_admin_role_permission_overrides_admin_id'), table_name='admin_role_permission_overrides')
    op.drop_table('admin_role_permission_overrides')
    op.drop_index(op.f('ix_accountants_phone'), table_name='accountants')
    op.drop_index(op.f('ix_accountants_employee_code'), table_name='accountants')
    op.drop_index(op.f('ix_accountants_email'), table_name='accountants')
    op.drop_index(op.f('ix_accountants_store_id'), table_name='accountants')
    op.drop_index(op.f('ix_accountants_admin_id'), table_name='accountants')
    op.drop_table('accountants')
    op.drop_index(op.f('ix_user_permission_overrides_user_type'), table_name='user_permission_overrides')
    op.drop_index(op.f('ix_user_permission_overrides_user_id'), table_name='user_permission_overrides')
    op.drop_index(op.f('ix_user_permission_overrides_permission_id'), table_name='user_permission_overrides')
    op.drop_index(op.f('ix_user_permission_overrides_admin_id'), table_name='user_permission_overrides')
    op.drop_table('user_permission_overrides')
    op.drop_index(op.f('ix_global_role_permissions_role_type'), table_name='global_role_permissions')
    op.drop_index(op.f('ix_global_role_permissions_permission_id'), table_name='global_role_permissions')
    op.drop_table('global_role_permissions')
    op.drop_index(op.f('ix_super_admins_email'), table_name='super_admins')
    op.drop_table('super_admins')
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_key'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_bill_settings_store_id'), table_name='bill_settings')
    op.drop_table('bill_settings')
    # ### end Alembic commands ###
