"""add_exchange_table

Revision ID: 85e7588a5867
Revises: 213fc7138f40
Create Date: 2026-07-06 16:01:13.820478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e7588a5867'
down_revision: Union[str, Sequence[str], None] = '213fc7138f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new values to transaction_type_enum in PostgreSQL
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute("COMMIT")
        try:
            op.execute("ALTER TYPE transaction_type_enum ADD VALUE 'EXCHANGE_IN'")
        except Exception:
            pass
        try:
            op.execute("ALTER TYPE transaction_type_enum ADD VALUE 'EXCHANGE_OUT'")
        except Exception:
            pass
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchanges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('exchange_number', sa.String(length=50), nullable=False, comment='Unique exchange number (e.g. EXC-2026-00001)'),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='FK → admins.id'),
    sa.Column('store_id', sa.BigInteger(), nullable=False, comment='FK → stores.id'),
    sa.Column('customer_id', sa.BigInteger(), nullable=True, comment='FK → customers.id'),
    sa.Column('original_sale_id', sa.BigInteger(), nullable=False, comment='FK → sales.id (exchanged from)'),
    sa.Column('original_sale_item_id', sa.BigInteger(), nullable=False, comment='FK → sale_items.id (returned item)'),
    sa.Column('new_sale_id', sa.BigInteger(), nullable=True, comment='FK → sales.id (new replacement sale)'),
    sa.Column('original_item_value', sa.Numeric(precision=12, scale=2), nullable=False, comment='Value of the returned item'),
    sa.Column('new_items_total', sa.Numeric(precision=12, scale=2), nullable=False, comment='Total value of replacement items'),
    sa.Column('exchange_credit', sa.Numeric(precision=12, scale=2), nullable=False, comment='Credit amount applied from original item'),
    sa.Column('additional_payment', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False, comment='Extra amount paid (new_items_total - exchange_credit)'),
    sa.Column('processed_by_type', sa.Enum('MANAGER', 'WORKER', 'OPTICIAN', name='staff_type_enum'), nullable=False, comment='Type of staff processing the exchange'),
    sa.Column('processed_by_id', sa.BigInteger(), nullable=False, comment='ID of staff processing the exchange'),
    sa.Column('exchange_date', sa.Date(), nullable=False, comment='Date of the exchange'),
    sa.Column('status', sa.Enum('COMPLETED', 'CANCELLED', name='exchange_status_enum', create_constraint=True), server_default='COMPLETED', nullable=False, comment='Lifecycle status of exchange'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Customer reason for exchange'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Internal notes / remarks'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['new_sale_id'], ['sales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['original_sale_id'], ['sales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['original_sale_item_id'], ['sale_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchanges_admin_id'), 'exchanges', ['admin_id'], unique=False)
    op.create_index(op.f('ix_exchanges_customer_id'), 'exchanges', ['customer_id'], unique=False)
    op.create_index(op.f('ix_exchanges_exchange_number'), 'exchanges', ['exchange_number'], unique=True)
    op.create_index(op.f('ix_exchanges_new_sale_id'), 'exchanges', ['new_sale_id'], unique=False)
    op.create_index(op.f('ix_exchanges_original_sale_id'), 'exchanges', ['original_sale_id'], unique=False)
    op.create_index(op.f('ix_exchanges_original_sale_item_id'), 'exchanges', ['original_sale_item_id'], unique=False)
    op.create_index(op.f('ix_exchanges_store_id'), 'exchanges', ['store_id'], unique=False)
    
    # Create product_units table
    op.create_table('product_units',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('unit_sku', sa.String(length=150), nullable=False, comment='Unique SKU per physical unit (e.g., FRM-RB-001-U0001)'),
    sa.Column('product_id', sa.BigInteger(), nullable=False, comment='FK → products.id'),
    sa.Column('inventory_batch_id', sa.BigInteger(), nullable=False, comment='FK → inventories.id — links unit to its cost batch'),
    sa.Column('status', sa.Enum('AVAILABLE', 'SOLD', 'DAMAGED', 'IN_REPAIR', 'LOST', 'RESERVED', name='unitstatus'), nullable=False, comment='Current physical status of this specific unit'),
    sa.Column('owner_type', sa.Enum('ADMIN', 'STORE', name='ownertype'), nullable=False, comment='Enum: ADMIN or STORE'),
    sa.Column('owner_id', sa.BigInteger(), nullable=False, comment='Polymorphic ID matching owner_type (admin.id or store.id)'),
    sa.Column('source_type', sa.Enum('PURCHASE_ORDER', 'MANUAL_ADD', 'TRANSFER_IN', 'RETURN', 'EXCHANGE_IN', name='unitsourcetype'), nullable=False, comment='How this unit entered the system'),
    sa.Column('manufacturer_serial', sa.String(length=255), nullable=True, comment='Optional external serial number from manufacturer'),
    sa.Column('sale_item_id', sa.BigInteger(), nullable=True, comment='FK → sale_items.id — tracks which sale item sold this unit'),
    sa.Column('repair_id', sa.BigInteger(), nullable=True, comment='FK → repairs.id — tracks if this unit is currently in repair'),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when status changed to SOLD'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when unit was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when unit was last updated'),
    sa.ForeignKeyConstraint(['inventory_batch_id'], ['inventories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repair_id'], ['repairs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_units_inventory_batch_id'), 'product_units', ['inventory_batch_id'], unique=False)
    op.create_index(op.f('ix_product_units_manufacturer_serial'), 'product_units', ['manufacturer_serial'], unique=False)
    op.create_index(op.f('ix_product_units_owner_id'), 'product_units', ['owner_id'], unique=False)
    op.create_index(op.f('ix_product_units_owner_type'), 'product_units', ['owner_type'], unique=False)
    op.create_index(op.f('ix_product_units_product_id'), 'product_units', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_units_repair_id'), 'product_units', ['repair_id'], unique=False)
    op.create_index(op.f('ix_product_units_sale_item_id'), 'product_units', ['sale_item_id'], unique=False)
    op.create_index(op.f('ix_product_units_status'), 'product_units', ['status'], unique=False)
    op.create_index(op.f('ix_product_units_unit_sku'), 'product_units', ['unit_sku'], unique=True)
    
    # Add product_unit_id to repairs
    op.add_column('repairs', sa.Column('product_unit_id', sa.BigInteger(), nullable=True, comment='FK → product_units.id — physical unit being repaired'))
    op.create_index(op.f('ix_repairs_product_unit_id'), 'repairs', ['product_unit_id'], unique=False)
    op.create_foreign_key(None, 'repairs', 'product_units', ['product_unit_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(None, 'repairs', type_='foreignkey')
    op.drop_index(op.f('ix_repairs_product_unit_id'), table_name='repairs')
    op.drop_column('repairs', 'product_unit_id')
    
    op.drop_index(op.f('ix_product_units_unit_sku'), table_name='product_units')
    op.drop_index(op.f('ix_product_units_status'), table_name='product_units')
    op.drop_index(op.f('ix_product_units_sale_item_id'), table_name='product_units')
    op.drop_index(op.f('ix_product_units_repair_id'), table_name='product_units')
    op.drop_index(op.f('ix_product_units_product_id'), table_name='product_units')
    op.drop_index(op.f('ix_product_units_owner_type'), table_name='product_units')
    op.drop_index(op.f('ix_product_units_owner_id'), table_name='product_units')
    op.drop_index(op.f('ix_product_units_manufacturer_serial'), table_name='product_units')
    op.drop_index(op.f('ix_product_units_inventory_batch_id'), table_name='product_units')
    op.drop_table('product_units')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchanges_store_id'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_original_sale_item_id'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_original_sale_id'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_new_sale_id'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_exchange_number'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_customer_id'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_admin_id'), table_name='exchanges')
    op.drop_table('exchanges')
    # ### end Alembic commands ###
