"""remove_roles_table

Revision ID: 869169d8fa20
Revises: a97771b1e73a
Create Date: 2026-06-02 16:47:02.337404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '869169d8fa20'
down_revision: Union[str, Sequence[str], None] = 'a97771b1e73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_store_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('store_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='FK → stores.id — the store this role belongs to'),
    sa.Column('role_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Role identifier — e.g., worker, optician, manager, cashier'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment="Human-readable description of the role's permissions"),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='Whether this role is currently active in the store'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Row last-update timestamp'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('roles_store_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey')),
    sa.UniqueConstraint('store_id', 'role_name', name=op.f('uq_store_role'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_roles_store_id'), 'roles', ['store_id'], unique=False)
    # ### end Alembic commands ###
