"""add_stock_aging_and_gst

Revision ID: 8cd2afd01a97
Revises: e1e19d00f2f9
Create Date: 2026-08-31 09:53:55.361642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_stock_aging_and_gst

Revision ID: 8cd2afd01a97
Revises: e1e19d00f2f9
Create Date: 2026-08-31 09:53:55.361642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd2afd01a97'
down_revision: Union[str, Sequence[str], None] = 'e1e19d00f2f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum type first
    aging_stage_enum = sa.Enum('NORMAL', 'STAGE_1', 'STAGE_2', 'STAGE_3', 'DEAD_STOCK', name='aging_stage_enum')
    aging_stage_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='FK → admins.id — Admin account this config applies to'),
    sa.Column('default_gst_percent', sa.Numeric(precision=5, scale=2), server_default='18.00', nullable=False, comment='Default GST rate percentage for all products (e.g. 18.00)'),
    sa.Column('aging_enabled', sa.Boolean(), server_default='true', nullable=False, comment='Flag to enable/disable automated stock aging'),
    sa.Column('normal_period_months', sa.Integer(), server_default='6', nullable=False, comment='Number of months a product stays in NORMAL status before discounting'),
    sa.Column('stage_1_months', sa.Integer(), server_default='3', nullable=False, comment='Number of months product stays in Stage 1 aging status'),
    sa.Column('stage_1_discount', sa.Numeric(precision=5, scale=2), server_default='10.00', nullable=False, comment='Discount percentage in Stage 1'),
    sa.Column('stage_2_months', sa.Integer(), server_default='3', nullable=False, comment='Number of months product stays in Stage 2 aging status'),
    sa.Column('stage_2_discount', sa.Numeric(precision=5, scale=2), server_default='20.00', nullable=False, comment='Discount percentage in Stage 2'),
    sa.Column('stage_3_months', sa.Integer(), server_default='3', nullable=False, comment='Number of months product stays in Stage 3 aging status'),
    sa.Column('stage_3_discount', sa.Numeric(precision=5, scale=2), server_default='50.00', nullable=False, comment='Discount percentage in Stage 3'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last record update timestamp'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_configs_admin_id'), 'inventory_configs', ['admin_id'], unique=True)
    op.create_table('product_aging_overrides',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('product_id', sa.BigInteger(), nullable=False, comment='FK → products.id — Product this override applies to'),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='FK → admins.id — Admin account owner'),
    sa.Column('aging_enabled', sa.Boolean(), nullable=True, comment='Override for automated aging status (True/False or NULL to inherit)'),
    sa.Column('normal_period_months', sa.Integer(), nullable=True, comment='Override for NORMAL period months (or NULL to inherit)'),
    sa.Column('stage_1_months', sa.Integer(), nullable=True, comment='Override for Stage 1 duration in months (or NULL to inherit)'),
    sa.Column('stage_1_discount', sa.Numeric(precision=5, scale=2), nullable=True, comment='Override for Stage 1 discount % (or NULL to inherit)'),
    sa.Column('stage_2_months', sa.Integer(), nullable=True, comment='Override for Stage 2 duration in months (or NULL to inherit)'),
    sa.Column('stage_2_discount', sa.Numeric(precision=5, scale=2), nullable=True, comment='Override for Stage 2 discount % (or NULL to inherit)'),
    sa.Column('stage_3_months', sa.Integer(), nullable=True, comment='Override for Stage 3 duration in months (or NULL to inherit)'),
    sa.Column('stage_3_discount', sa.Numeric(precision=5, scale=2), nullable=True, comment='Override for Stage 3 discount % (or NULL to inherit)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last record update timestamp'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_aging_overrides_admin_id'), 'product_aging_overrides', ['admin_id'], unique=False)
    op.create_index(op.f('ix_product_aging_overrides_product_id'), 'product_aging_overrides', ['product_id'], unique=True)
    op.add_column('inventories', sa.Column('aging_stage', sa.Enum('NORMAL', 'STAGE_1', 'STAGE_2', 'STAGE_3', 'DEAD_STOCK', name='aging_stage_enum', create_constraint=True), server_default='NORMAL', nullable=False, comment='Current aging stage of this inventory batch'))
    op.add_column('inventories', sa.Column('aging_discount_percent', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False, comment='Aging-related discount percentage currently applicable'))
    op.add_column('inventories', sa.Column('aging_stage_changed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the aging stage was last transitioned'))
    op.add_column('products', sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=True, comment='Custom GST rate percentage override for this product (NULL to inherit default)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'gst_percent')
    op.drop_column('inventories', 'aging_stage_changed_at')
    op.drop_column('inventories', 'aging_discount_percent')
    op.drop_column('inventories', 'aging_stage')
    op.drop_index(op.f('ix_product_aging_overrides_product_id'), table_name='product_aging_overrides')
    op.drop_index(op.f('ix_product_aging_overrides_admin_id'), table_name='product_aging_overrides')
    op.drop_table('product_aging_overrides')
    op.drop_index(op.f('ix_inventory_configs_admin_id'), table_name='inventory_configs')
    op.drop_table('inventory_configs')
    # ### end Alembic commands ###

    # Drop enum type
    aging_stage_enum = sa.Enum('NORMAL', 'STAGE_1', 'STAGE_2', 'STAGE_3', 'DEAD_STOCK', name='aging_stage_enum')
    aging_stage_enum.drop(op.get_bind(), checkfirst=True)
