"""add_inventory_management_module

Revision ID: 90c51bdf11ad
Revises: 869169d8fa20
Create Date: 2026-06-03 13:55:41.342639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c51bdf11ad'
down_revision: Union[str, Sequence[str], None] = '869169d8fa20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='FK → admins.id — owner of this brand record'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Brand display name (e.g. Ray-Ban, Titan)'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether the brand is currently active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_admin_id'), 'brands', ['admin_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='FK → admins.id — owner of this category'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Category display name (e.g. Frames, Lenses, Accessories)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of the category'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether the category is currently active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_admin_id'), 'categories', ['admin_id'], unique=False)
    op.create_table('subcategories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('category_id', sa.BigInteger(), nullable=False, comment='FK → categories.id — parent category'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Subcategory display name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of the subcategory'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether the subcategory is currently active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcategories_category_id'), 'subcategories', ['category_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='FK → admins.id — owner of this product (multi-tenant)'),
    sa.Column('category_id', sa.BigInteger(), nullable=False, comment='FK → categories.id — top-level category'),
    sa.Column('subcategory_id', sa.BigInteger(), nullable=True, comment='FK → subcategories.id — optional finer classification'),
    sa.Column('sku', sa.String(length=100), nullable=False, comment='Stock Keeping Unit — unique product identifier'),
    sa.Column('barcode', sa.String(length=100), nullable=True, comment='Optional barcode (EAN / UPC)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Product display name'),
    sa.Column('brand_id', sa.BigInteger(), nullable=True, comment='FK → brands.id — manufacturer / brand'),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Purchase / cost price'),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Retail selling price'),
    sa.Column('image_url', sa.Text(), nullable=True, comment='URL or path to the product image'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether the product is currently active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_index(op.f('ix_products_admin_id'), 'products', ['admin_id'], unique=False)
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_subcategory_id'), 'products', ['subcategory_id'], unique=False)
    op.create_table('accessory_products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('product_id', sa.BigInteger(), nullable=False, comment='FK → products.id — one-to-one link to base product'),
    sa.Column('accessory_type', sa.String(length=100), nullable=True, comment='Accessory type (e.g. Case, Cloth, Chain, Solution)'),
    sa.Column('material', sa.String(length=100), nullable=True, comment='Accessory material'),
    sa.Column('color', sa.String(length=100), nullable=True, comment='Accessory color'),
    sa.Column('size', sa.String(length=100), nullable=True, comment='Accessory size / dimensions'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('frame_products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('product_id', sa.BigInteger(), nullable=False, comment='FK → products.id — one-to-one link to base product'),
    sa.Column('frame_type', sa.String(length=100), nullable=True, comment='Frame type (e.g. Full-Rim, Half-Rim, Rimless)'),
    sa.Column('shape', sa.String(length=100), nullable=True, comment='Frame shape (e.g. Rectangle, Round, Aviator, Cat-Eye)'),
    sa.Column('material', sa.String(length=100), nullable=True, comment='Frame material (e.g. Acetate, Metal, TR-90, Titanium)'),
    sa.Column('color', sa.String(length=100), nullable=True, comment='Frame color'),
    sa.Column('lens_width', sa.String(length=100), nullable=True, comment='Lens width in mm'),
    sa.Column('bridge_width', sa.String(length=100), nullable=True, comment='Bridge width in mm'),
    sa.Column('temple_length', sa.String(length=100), nullable=True, comment='Temple length in mm'),
    sa.Column('gender', sa.String(length=100), nullable=True, comment='Target gender (e.g. Male, Female, Unisex)'),
    sa.Column('age_group', sa.String(length=100), nullable=True, comment='Target age group (e.g. Adult, Kids)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('inventories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('owner_type', sa.Enum('ADMIN', 'STORE', name='owner_type_enum', create_constraint=True), nullable=False, comment='Owner type: ADMIN (warehouse) or STORE'),
    sa.Column('owner_id', sa.BigInteger(), nullable=False, comment='Polymorphic FK — admins.id when ADMIN, stores.id when STORE'),
    sa.Column('product_id', sa.BigInteger(), nullable=False, comment='FK → products.id — the product being tracked'),
    sa.Column('quantity', sa.Integer(), server_default='0', nullable=False, comment='Total physical quantity on hand'),
    sa.Column('reserved_quantity', sa.Integer(), server_default='0', nullable=False, comment='Quantity reserved for pending orders'),
    sa.Column('available_quantity', sa.Integer(), server_default='0', nullable=False, comment='quantity - reserved_quantity = available for sale'),
    sa.Column('reorder_level', sa.Integer(), server_default='0', nullable=False, comment='Threshold below which restocking is needed'),
    sa.Column('last_purchase_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Price paid in the most recent purchase'),
    sa.Column('last_stock_in_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last stock inflow'),
    sa.Column('last_stock_out_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last stock outflow'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether this inventory record is active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_type', 'owner_id', 'product_id', name='uq_inventory_owner_product')
    )
    op.create_index(op.f('ix_inventories_owner_id'), 'inventories', ['owner_id'], unique=False)
    op.create_index(op.f('ix_inventories_product_id'), 'inventories', ['product_id'], unique=False)
    op.create_table('lens_products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('product_id', sa.BigInteger(), nullable=False, comment='FK → products.id — one-to-one link to base product'),
    sa.Column('lens_type', sa.String(length=100), nullable=True, comment='Lens type (e.g. Single Vision, Bifocal, Progressive)'),
    sa.Column('material', sa.String(length=100), nullable=True, comment='Lens material (e.g. CR-39, Polycarbonate, Glass, Trivex)'),
    sa.Column('index_value', sa.String(length=100), nullable=True, comment='Refractive index (e.g. 1.50, 1.56, 1.60, 1.67, 1.74)'),
    sa.Column('coating', sa.String(length=100), nullable=True, comment='Coating type (e.g. Anti-Reflective, Scratch-Resistant, HMC)'),
    sa.Column('tint_color', sa.String(length=100), nullable=True, comment='Tint color if applicable'),
    sa.Column('uv_protection', sa.String(length=100), nullable=True, comment='UV protection level (e.g. UV400, UV380)'),
    sa.Column('blue_cut', sa.String(length=100), nullable=True, comment='Blue-light filtering (e.g. Yes, No, Percentage)'),
    sa.Column('photochromic', sa.String(length=100), nullable=True, comment='Photochromic / transition capability'),
    sa.Column('polarized', sa.String(length=100), nullable=True, comment='Polarization (e.g. Yes, No)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('inventory_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('inventory_id', sa.BigInteger(), nullable=False, comment='FK → inventories.id — the inventory record affected'),
    sa.Column('product_id', sa.BigInteger(), nullable=False, comment='FK → products.id — denormalised for faster queries'),
    sa.Column('transaction_type', sa.Enum('PURCHASE', 'SALE', 'ADMIN_TRANSFER_OUT', 'ADMIN_TRANSFER_IN', 'STORE_TRANSFER_OUT', 'STORE_TRANSFER_IN', 'DAMAGE', 'LOSS', 'AUDIT_ADJUSTMENT', 'RETURN', name='transaction_type_enum', create_constraint=True), nullable=False, comment='Type of inventory movement'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Number of units moved (always positive)'),
    sa.Column('send_store_id', sa.BigInteger(), nullable=True, comment='FK → stores.id — source store for transfers'),
    sa.Column('receive_store_id', sa.BigInteger(), nullable=True, comment='FK → stores.id — destination store for transfers'),
    sa.Column('reference_id', sa.BigInteger(), nullable=True, comment='Optional reference to related entity (e.g. order_id, purchase_order_id)'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='Optional notes / reason for the transaction'),
    sa.Column('created_by', sa.BigInteger(), nullable=False, comment='User ID who initiated this transaction'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Transaction timestamp'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receive_store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['send_store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_inventory_id'), 'inventory_transactions', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_product_id'), 'inventory_transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_receive_store_id'), 'inventory_transactions', ['receive_store_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_send_store_id'), 'inventory_transactions', ['send_store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_transactions_send_store_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_receive_store_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_product_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_inventory_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_table('lens_products')
    op.drop_index(op.f('ix_inventories_product_id'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_owner_id'), table_name='inventories')
    op.drop_table('inventories')
    op.drop_table('frame_products')
    op.drop_table('accessory_products')
    op.drop_index(op.f('ix_products_subcategory_id'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_index(op.f('ix_products_admin_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_subcategories_category_id'), table_name='subcategories')
    op.drop_table('subcategories')
    op.drop_index(op.f('ix_categories_admin_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_admin_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
