"""create_managers_table

Revision ID: a97771b1e73a
Revises: 19bf4bfa7d32
Create Date: 2026-06-02 16:12:37.952748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97771b1e73a'
down_revision: Union[str, Sequence[str], None] = '19bf4bfa7d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('store_id', sa.BigInteger(), nullable=False, comment='FK → stores.id — the store this manager belongs to'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment="Manager's first name"),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment="Manager's last name"),
    sa.Column('email', sa.String(length=255), nullable=True, comment="Manager's email (optional but unique if provided)"),
    sa.Column('phone', sa.String(length=10), nullable=False, comment='10-digit phone number'),
    sa.Column('password_hash', sa.Text(), nullable=False, comment="bcrypt hash (cost=12) of the manager's password"),
    sa.Column('profile_image', sa.Text(), nullable=True, comment='URL or path to profile image'),
    sa.Column('employee_code', sa.String(length=50), nullable=False, comment='Unique employee identifier code'),
    sa.Column('joining_date', sa.Date(), nullable=False, comment='Date the manager joined'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether the manager is currently active'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Updated on every successful login'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp — NULL means active'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managers_email'), 'managers', ['email'], unique=True)
    op.create_index(op.f('ix_managers_employee_code'), 'managers', ['employee_code'], unique=True)
    op.create_index(op.f('ix_managers_phone'), 'managers', ['phone'], unique=True)
    op.create_index(op.f('ix_managers_store_id'), 'managers', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managers_store_id'), table_name='managers')
    op.drop_index(op.f('ix_managers_phone'), table_name='managers')
    op.drop_index(op.f('ix_managers_employee_code'), table_name='managers')
    op.drop_index(op.f('ix_managers_email'), table_name='managers')
    op.drop_table('managers')
    # ### end Alembic commands ###
