"""add_qc_models_and_permissions

Revision ID: b224edc31216
Revises: h1a2b3c4d5e6
Create Date: 2026-09-05 09:43:46.588883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b224edc31216'
down_revision: Union[str, Sequence[str], None] = 'h1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qc_customer_contact_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('sale_item_id', sa.BigInteger(), nullable=False, comment='FK → sale_items.id — order line item discussed'),
    sa.Column('logged_by_id', sa.BigInteger(), nullable=False, comment='User ID who logged this contact event'),
    sa.Column('logged_by_name', sa.String(length=150), nullable=True, comment='Cached display name of staff member'),
    sa.Column('contact_channel', sa.String(length=50), nullable=False, comment='PHONE, WHATSAPP, or EMAIL_SYSTEM'),
    sa.Column('summary_notes', sa.Text(), nullable=False, comment='Summary of discussion, agreement, or customer feedback'),
    sa.Column('customer_choice', sa.String(length=50), nullable=True, comment='WAIT_FOR_STOCK, CHOOSE_DIFFERENT_ITEM, REFUND_ITEM, or NULL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of contact log entry'),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_customer_contact_logs_sale_item_id'), 'qc_customer_contact_logs', ['sale_item_id'], unique=False)
    op.create_table('qc_damaged_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='FK → admins.id — tenant business scope'),
    sa.Column('store_id', sa.BigInteger(), nullable=False, comment='FK → stores.id — store where damage occurred/inspected'),
    sa.Column('sale_item_id', sa.BigInteger(), nullable=False, comment='FK → sale_items.id — order line item flagged as damaged'),
    sa.Column('product_id', sa.BigInteger(), nullable=False, comment='FK → products.id — product damaged'),
    sa.Column('supplier_id', sa.BigInteger(), nullable=True, comment='FK → suppliers.id — supplier liable for STOCK_DAMAGE'),
    sa.Column('lab_id', sa.BigInteger(), nullable=True, comment='FK → labs.id — lab liable for LAB_DAMAGE'),
    sa.Column('damage_type', sa.String(length=50), nullable=False, comment='STOCK_DAMAGE (damaged before lab) or LAB_DAMAGE (damaged during lab processing)'),
    sa.Column('stage', sa.String(length=50), nullable=False, comment='PRE_LAB or POST_LAB'),
    sa.Column('warranty_status', sa.String(length=50), server_default='UNKNOWN', nullable=False, comment='IN_WARRANTY, OUT_OF_WARRANTY, or UNKNOWN'),
    sa.Column('compensation_type', sa.String(length=50), server_default='PENDING', nullable=False, comment='REPLACEMENT_ITEM, EQUIVALENT_ITEM, CASH_REFUND, CREDIT_NOTE, or PENDING'),
    sa.Column('compensation_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Monetary value of credit note/refund compensation'),
    sa.Column('supplier_payment_id', sa.BigInteger(), nullable=True, comment='FK → supplier_payments.id — ledger entry recording credit note/compensation'),
    sa.Column('status', sa.String(length=50), server_default='OPEN', nullable=False, comment='Lifecycle status: OPEN, CLAIM_FILED, RESOLVED, WRITTEN_OFF'),
    sa.Column('resolution_notes', sa.Text(), nullable=True, comment='Detailed log of supplier claim, credit note details, or lab settlement'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when damage record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when damage record was last updated'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_payment_id'], ['supplier_payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_damaged_items_admin_id'), 'qc_damaged_items', ['admin_id'], unique=False)
    op.create_index(op.f('ix_qc_damaged_items_lab_id'), 'qc_damaged_items', ['lab_id'], unique=False)
    op.create_index(op.f('ix_qc_damaged_items_product_id'), 'qc_damaged_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_qc_damaged_items_sale_item_id'), 'qc_damaged_items', ['sale_item_id'], unique=False)
    op.create_index(op.f('ix_qc_damaged_items_store_id'), 'qc_damaged_items', ['store_id'], unique=False)
    op.create_index(op.f('ix_qc_damaged_items_supplier_id'), 'qc_damaged_items', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_qc_damaged_items_supplier_payment_id'), 'qc_damaged_items', ['supplier_payment_id'], unique=False)
    op.create_table('sale_item_qc_histories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('sale_item_id', sa.BigInteger(), nullable=False, comment='FK → sale_items.id — individual item inspected'),
    sa.Column('sale_id', sa.BigInteger(), nullable=False, comment='FK → sales.id — order containing this item'),
    sa.Column('inspector_id', sa.BigInteger(), nullable=False, comment='User ID of inspector who performed this QC action'),
    sa.Column('inspector_type', sa.String(length=50), nullable=False, comment='Role/type of inspector (e.g. ADMIN, MANAGER, OPTICIAN, WORKER)'),
    sa.Column('inspector_name', sa.String(length=150), nullable=True, comment='Cached display name of inspector'),
    sa.Column('previous_status', sa.String(length=50), nullable=True, comment='QC status before this transition'),
    sa.Column('new_status', sa.String(length=50), nullable=False, comment='QC status resulting from this inspection'),
    sa.Column('damage_type', sa.String(length=50), nullable=True, comment='STOCK_DAMAGE, LAB_DAMAGE, or FITTING_FAILURE (if failed)'),
    sa.Column('rework_cycle', sa.Integer(), server_default='0', nullable=False, comment='Iteration number of rework cycle (0 for normal, 1+ for fitting reworks)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Inspector observations, fault descriptions, or rework instructions'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of inspection event'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_item_qc_histories_sale_id'), 'sale_item_qc_histories', ['sale_id'], unique=False)
    op.create_index(op.f('ix_sale_item_qc_histories_sale_item_id'), 'sale_item_qc_histories', ['sale_item_id'], unique=False)
    op.add_column('sale_items', sa.Column('qc_status', sa.String(length=50), server_default='PENDING_QC_PRE_LAB', nullable=False, comment='Current per-item QC status (e.g. PENDING_QC_PRE_LAB, QC_PASSED_PRE_LAB, QC_FAILED_PRE_LAB, SENT_TO_LAB, LAB_IN_PROGRESS, RETURNED_FROM_LAB, PENDING_QC_POST_LAB, QC_PASSED_POST_LAB, QC_FAILED_POST_LAB, DELIVERED)'))
    op.add_column('sale_items', sa.Column('damage_type', sa.String(length=50), nullable=True, comment='Categorization if QC failed: STOCK_DAMAGE, LAB_DAMAGE, or FITTING_FAILURE'))
    op.add_column('sale_items', sa.Column('rework_count', sa.Integer(), server_default='0', nullable=False, comment='Number of rework cycles completed for fitting failures'))
    op.add_column('sale_items', sa.Column('resolution_status', sa.String(length=50), server_default='UNRESOLVED', nullable=False, comment='Resolution tracking: UNRESOLVED, REPLACED_FROM_STOCK, TRANSFER_REQUESTED, REWORK_IN_PROGRESS, SUPPLIER_CLAIM_PENDING, LAB_CLAIM_PENDING, CUSTOMER_DECISION_PENDING, RESOLVED'))
    op.add_column('sale_items', sa.Column('customer_notified', sa.Boolean(), server_default='false', nullable=False, comment='True if customer has been notified regarding item issues or choices'))
    op.add_column('sale_items', sa.Column('customer_decision', sa.String(length=50), nullable=True, comment='Customer choice: WAIT_FOR_STOCK, CHOOSE_DIFFERENT_ITEM, REFUND_ITEM'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_items', 'customer_decision')
    op.drop_column('sale_items', 'customer_notified')
    op.drop_column('sale_items', 'resolution_status')
    op.drop_column('sale_items', 'rework_count')
    op.drop_column('sale_items', 'damage_type')
    op.drop_column('sale_items', 'qc_status')
    op.drop_index(op.f('ix_sale_item_qc_histories_sale_item_id'), table_name='sale_item_qc_histories')
    op.drop_index(op.f('ix_sale_item_qc_histories_sale_id'), table_name='sale_item_qc_histories')
    op.drop_table('sale_item_qc_histories')
    op.drop_index(op.f('ix_qc_damaged_items_supplier_payment_id'), table_name='qc_damaged_items')
    op.drop_index(op.f('ix_qc_damaged_items_supplier_id'), table_name='qc_damaged_items')
    op.drop_index(op.f('ix_qc_damaged_items_store_id'), table_name='qc_damaged_items')
    op.drop_index(op.f('ix_qc_damaged_items_sale_item_id'), table_name='qc_damaged_items')
    op.drop_index(op.f('ix_qc_damaged_items_product_id'), table_name='qc_damaged_items')
    op.drop_index(op.f('ix_qc_damaged_items_lab_id'), table_name='qc_damaged_items')
    op.drop_index(op.f('ix_qc_damaged_items_admin_id'), table_name='qc_damaged_items')
    op.drop_table('qc_damaged_items')
    op.drop_index(op.f('ix_qc_customer_contact_logs_sale_item_id'), table_name='qc_customer_contact_logs')
    op.drop_table('qc_customer_contact_logs')
    # ### end Alembic commands ###
