"""add_sales_workflow_type

Revision ID: b9efad8eb625
Revises: 82b3e9e66626
Create Date: 2026-09-02 22:12:03.692605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9efad8eb625'
down_revision: Union[str, Sequence[str], None] = '82b3e9e66626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('sales_workflow_type', sa.String(length=50), server_default='BOTH', nullable=False, comment='Default workflow eligibility for products in this category: DIRECT_ONLY, ORDER_ONLY, or BOTH'))
    op.add_column('products', sa.Column('sales_workflow_type', sa.String(length=50), server_default='BOTH', nullable=False, comment='Workflow eligibility: DIRECT_ONLY, ORDER_ONLY, or BOTH'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sales_workflow_type')
    op.drop_column('categories', 'sales_workflow_type')
    # ### end Alembic commands ###
