"""add_low_stock_threshold_to_products

Revision ID: e1e19d00f2f9
Revises: d4e5f6a7b8c9
Create Date: 2026-08-31 08:47:14.307198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e19d00f2f9'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('low_stock_threshold', sa.Integer(), nullable=True, comment='Low stock threshold for this product'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'low_stock_threshold')
    # ### end Alembic commands ###
