"""add_supplier_and_sales_modules

Revision ID: e2d9966df673
Revises: 90c51bdf11ad
Create Date: 2026-06-04 14:41:46.698991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d9966df673'
down_revision: Union[str, Sequence[str], None] = '90c51bdf11ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='FK → admins.id — the business that owns this supplier record'),
    sa.Column('company_name', sa.String(length=255), nullable=False, comment="Supplier's company / business name"),
    sa.Column('contact_person', sa.String(length=200), nullable=True, comment='Primary contact person at the supplier'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Supplier contact email'),
    sa.Column('phone', sa.String(length=10), nullable=True, comment='Supplier primary phone (10 digits)'),
    sa.Column('alternate_phone', sa.String(length=10), nullable=True, comment='Alternate phone number'),
    sa.Column('address', sa.Text(), nullable=True, comment='Supplier address'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='City'),
    sa.Column('state', sa.String(length=100), nullable=True, comment='State'),
    sa.Column('pincode', sa.String(length=6), nullable=True, comment='6-digit pincode'),
    sa.Column('gst_number', sa.String(length=15), nullable=True, comment='Supplier GST registration number'),
    sa.Column('pan_number', sa.String(length=10), nullable=True, comment='Supplier PAN number'),
    sa.Column('bank_account_number', sa.String(length=20), nullable=True, comment='Bank account number for payment transfers'),
    sa.Column('bank_ifsc', sa.String(length=11), nullable=True, comment="IFSC code of supplier's bank branch"),
    sa.Column('bank_name', sa.String(length=100), nullable=True, comment='Bank name'),
    sa.Column('credit_days', sa.BigInteger(), server_default='0', nullable=False, comment='Default credit period (days) agreed with this supplier'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLACKLISTED', name='supplier_status_enum', create_constraint=True), server_default='ACTIVE', nullable=False, comment='Supplier status: ACTIVE, INACTIVE, or BLACKLISTED'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Internal notes about this supplier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp — NULL means active'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_admin_id'), 'suppliers', ['admin_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='FK → admins.id — the business this customer belongs to'),
    sa.Column('first_visit_store_id', sa.BigInteger(), nullable=True, comment='FK → stores.id — store where customer was first registered'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='Customer first name'),
    sa.Column('last_name', sa.String(length=100), nullable=True, comment='Customer last name'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Customer email (optional)'),
    sa.Column('phone', sa.String(length=10), nullable=False, comment='Customer phone — primary identifier'),
    sa.Column('date_of_birth', sa.Date(), nullable=True, comment='Date of birth — used for birthday campaigns'),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'NOT_SPECIFIED', name='customer_gender_enum', create_constraint=True), server_default='NOT_SPECIFIED', nullable=False, comment='Customer gender'),
    sa.Column('address', sa.Text(), nullable=True, comment='Customer address'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='City'),
    sa.Column('state', sa.String(length=100), nullable=True, comment='State'),
    sa.Column('pincode', sa.String(length=6), nullable=True, comment='Pincode'),
    sa.Column('prescription_sph_right', sa.String(length=10), nullable=True, comment='Right eye sphere power (e.g. -2.50)'),
    sa.Column('prescription_cyl_right', sa.String(length=10), nullable=True, comment='Right eye cylinder power'),
    sa.Column('prescription_axis_right', sa.String(length=10), nullable=True, comment='Right eye axis'),
    sa.Column('prescription_sph_left', sa.String(length=10), nullable=True, comment='Left eye sphere power'),
    sa.Column('prescription_cyl_left', sa.String(length=10), nullable=True, comment='Left eye cylinder power'),
    sa.Column('prescription_axis_left', sa.String(length=10), nullable=True, comment='Left eye axis'),
    sa.Column('prescription_add', sa.String(length=10), nullable=True, comment='Addition (near vision) power'),
    sa.Column('prescription_date', sa.Date(), nullable=True, comment='Date of the prescription'),
    sa.Column('prescription_notes', sa.Text(), nullable=True, comment='Optician notes on the prescription'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Internal CRM notes about this customer'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether customer record is active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['first_visit_store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_admin_id'), 'customers', ['admin_id'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_first_visit_store_id'), 'customers', ['first_visit_store_id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('po_number', sa.String(length=50), nullable=False, comment='Human-readable PO reference number (e.g. PO-2024-00001)'),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='FK → admins.id — owner of the PO'),
    sa.Column('store_id', sa.BigInteger(), nullable=True, comment='FK → stores.id — NULL means admin/warehouse-level order'),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False, comment='FK → suppliers.id — which supplier this PO is sent to'),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED', name='po_status_enum', create_constraint=True), server_default='DRAFT', nullable=False, comment='PO lifecycle status'),
    sa.Column('order_date', sa.Date(), nullable=False, comment='Date the PO was raised'),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True, comment='Expected date of goods receipt'),
    sa.Column('received_date', sa.Date(), nullable=True, comment='Actual date goods were received (fully)'),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False, comment='Sum of all line item totals before tax'),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False, comment='Total GST / tax charged by the supplier'),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False, comment='Total discount given by the supplier'),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False, comment='subtotal + tax_amount - discount_amount'),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False, comment='Total amount paid to the supplier so far'),
    sa.Column('due_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False, comment='total_amount - paid_amount (outstanding balance)'),
    sa.Column('due_date', sa.Date(), nullable=True, comment='Payment due date based on credit terms'),
    sa.Column('invoice_number', sa.String(length=100), nullable=True, comment="Supplier's invoice number (filled on receipt)"),
    sa.Column('notes', sa.Text(), nullable=True, comment='Internal notes about this purchase order'),
    sa.Column('created_by', sa.BigInteger(), nullable=False, comment='User ID (admin / manager) who created this PO'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_admin_id'), 'purchase_orders', ['admin_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_store_id'), 'purchase_orders', ['store_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('supplier_store_links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False, comment='FK → suppliers.id'),
    sa.Column('store_id', sa.BigInteger(), nullable=False, comment='FK → stores.id — the store this supplier is linked to'),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False, comment="Whether this is the store's primary/preferred supplier"),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether this supplier-store relationship is active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'store_id', name='uq_supplier_store')
    )
    op.create_index(op.f('ix_supplier_store_links_store_id'), 'supplier_store_links', ['store_id'], unique=False)
    op.create_index(op.f('ix_supplier_store_links_supplier_id'), 'supplier_store_links', ['supplier_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('invoice_number', sa.String(length=50), nullable=False, comment='Human-readable invoice number (e.g. INV-2024-00001)'),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='FK → admins.id — owning business (for multi-tenant queries)'),
    sa.Column('store_id', sa.BigInteger(), nullable=False, comment='FK → stores.id — store where the sale happened'),
    sa.Column('customer_id', sa.BigInteger(), nullable=True, comment='FK → customers.id — NULL for walk-in anonymous sales'),
    sa.Column('sold_by_type', sa.Enum('MANAGER', 'WORKER', 'OPTICIAN', name='staff_type_enum', create_constraint=True), nullable=False, comment='Type of staff member who handled the sale'),
    sa.Column('sold_by_id', sa.BigInteger(), nullable=False, comment='Polymorphic FK — managers.id / workers.id / opticians.id'),
    sa.Column('sale_date', sa.Date(), nullable=False, comment='Date the sale was made'),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'PARTIALLY_PAID', 'CANCELLED', 'REFUNDED', name='sale_status_enum', create_constraint=True), server_default='COMPLETED', nullable=False, comment='Sale lifecycle status'),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False, comment='Sum of all line item totals before discount and tax'),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False, comment='Total discount given on this sale'),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False, comment='Total tax (GST) on this sale'),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='subtotal - discount_amount + tax_amount'),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False, comment='Total amount paid by the customer so far'),
    sa.Column('due_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False, comment='total_amount - paid_amount'),
    sa.Column('loyalty_points_earned', sa.BigInteger(), server_default='0', nullable=False, comment='Loyalty points awarded on this sale'),
    sa.Column('loyalty_points_redeemed', sa.BigInteger(), server_default='0', nullable=False, comment='Loyalty points redeemed on this sale'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional notes / special instructions for this sale'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_admin_id'), 'sales', ['admin_id'], unique=False)
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_invoice_number'), 'sales', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_sales_sold_by_id'), 'sales', ['sold_by_id'], unique=False)
    op.create_index(op.f('ix_sales_store_id'), 'sales', ['store_id'], unique=False)
    op.create_table('supplier_payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('purchase_order_id', sa.BigInteger(), nullable=False, comment='FK → purchase_orders.id — the PO this payment is against'),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False, comment='FK → suppliers.id — denormalised for faster supplier ledger queries'),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='FK → admins.id — owning business'),
    sa.Column('payment_date', sa.Date(), nullable=False, comment='Date the payment was made'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Amount paid in this transaction'),
    sa.Column('payment_method', sa.Enum('CASH', 'BANK_TRANSFER', 'UPI', 'CHEQUE', 'CREDIT_NOTE', name='supplier_payment_method_enum', create_constraint=True), nullable=False, comment='How the payment was made'),
    sa.Column('reference_number', sa.String(length=100), nullable=True, comment='UTR / cheque number / UPI transaction ID'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='Optional notes about this payment'),
    sa.Column('created_by', sa.BigInteger(), nullable=False, comment='User ID who recorded this payment'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_payments_admin_id'), 'supplier_payments', ['admin_id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_purchase_order_id'), 'supplier_payments', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_supplier_id'), 'supplier_payments', ['supplier_id'], unique=False)
    op.create_table('sale_payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('sale_id', sa.BigInteger(), nullable=False, comment='FK → sales.id'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Amount paid in this transaction'),
    sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'UPI', 'BANK_TRANSFER', 'LOYALTY_POINTS', 'CREDIT', 'CHEQUE', name='sale_payment_method_enum', create_constraint=True), nullable=False, comment='Payment method used'),
    sa.Column('reference_number', sa.String(length=100), nullable=True, comment='Transaction reference / UPI ID / card last-4'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='Optional remarks'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_payments_sale_id'), 'sale_payments', ['sale_id'], unique=False)
    op.create_table('supplier_products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False, comment='FK → suppliers.id'),
    sa.Column('product_id', sa.BigInteger(), nullable=False, comment='FK → products.id — the product this supplier can provide'),
    sa.Column('supplier_sku', sa.String(length=100), nullable=True, comment="Supplier's own SKU / part number for this product"),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False, comment="Supplier's quoted unit price (purchase price from supplier)"),
    sa.Column('minimum_order_quantity', sa.BigInteger(), server_default='1', nullable=False, comment='Minimum units the supplier will sell in one order'),
    sa.Column('lead_time_days', sa.BigInteger(), nullable=True, comment='Expected lead time in days from order to delivery'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether this supplier still provides this product'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'product_id', name='uq_supplier_product')
    )
    op.create_index(op.f('ix_supplier_products_product_id'), 'supplier_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_supplier_products_supplier_id'), 'supplier_products', ['supplier_id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('purchase_order_id', sa.BigInteger(), nullable=False, comment='FK → purchase_orders.id'),
    sa.Column('product_id', sa.BigInteger(), nullable=False, comment='FK → products.id — product being ordered'),
    sa.Column('inventory_id', sa.BigInteger(), nullable=True, comment='FK → inventories.id — target inventory record to update on receipt'),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False, comment='Number of units ordered'),
    sa.Column('quantity_received', sa.Integer(), server_default='0', nullable=False, comment='Number of units actually received (updated on GRN)'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Agreed unit price from supplier at time of order'),
    sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False, comment='GST % applied to this line item'),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False, comment='Line-item discount percentage'),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False, comment='(unit_price × qty_ordered × (1 - discount/100)) + tax'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notes for this specific line item'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_inventory_id'), 'purchase_order_items', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_product_id'), 'purchase_order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_purchase_order_id'), 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-generated BIGINT primary key'),
    sa.Column('sale_id', sa.BigInteger(), nullable=False, comment='FK → sales.id'),
    sa.Column('product_id', sa.BigInteger(), nullable=False, comment='FK → products.id — product sold'),
    sa.Column('inventory_id', sa.BigInteger(), nullable=True, comment='FK → inventories.id — inventory record decremented by this sale'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Number of units sold'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Selling price per unit at time of sale'),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True, comment='Cost price per unit at time of sale (for margin reporting)'),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False, comment='Discount percentage on this line item'),
    sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False, comment='GST / tax percentage on this line item'),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False, comment='(unit_price × qty × (1 - discount/100)) + tax'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional notes for this line item (e.g. custom lens specs)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row last-update timestamp'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_items_inventory_id'), 'sale_items', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_sale_items_product_id'), 'sale_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_product_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_inventory_id'), table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index(op.f('ix_purchase_order_items_purchase_order_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_product_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_inventory_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_supplier_products_supplier_id'), table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_product_id'), table_name='supplier_products')
    op.drop_table('supplier_products')
    op.drop_index(op.f('ix_sale_payments_sale_id'), table_name='sale_payments')
    op.drop_table('sale_payments')
    op.drop_index(op.f('ix_supplier_payments_supplier_id'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_purchase_order_id'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_admin_id'), table_name='supplier_payments')
    op.drop_table('supplier_payments')
    op.drop_index(op.f('ix_sales_store_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_sold_by_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_invoice_number'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_admin_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_supplier_store_links_supplier_id'), table_name='supplier_store_links')
    op.drop_index(op.f('ix_supplier_store_links_store_id'), table_name='supplier_store_links')
    op.drop_table('supplier_store_links')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_store_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_admin_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_first_visit_store_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_admin_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_suppliers_admin_id'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
