"""add_pf_number_to_staff_tables

Revision ID: f3a1b2c4d5e6
Revises: daeaaad90134
Create Date: 2026-06-19 14:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a1b2c4d5e6'
down_revision: Union[str, Sequence[str], None] = 'daeaaad90134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('pf_number', sa.String(length=50), nullable=True, comment='Provident Fund number (optional)'))
    op.add_column('opticians', sa.Column('pf_number', sa.String(length=50), nullable=True, comment='Provident Fund number (optional)'))
    op.add_column('workers', sa.Column('pf_number', sa.String(length=50), nullable=True, comment='Provident Fund number (optional)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'pf_number')
    op.drop_column('opticians', 'pf_number')
    op.drop_column('managers', 'pf_number')
    # ### end Alembic commands ###
